package Pagesmith::Form::Constants;
## Some constatns for forms
## Author         : js5
## Maintainer     : js5
## Created        : 2009-08-12
## Last commit by : $Author$
## Last modified  : $Date$
## Revision       : $Revision$
## Repository URL : $HeadURL$

use strict;
use warnings;
use utf8;

use version qw(qv); our $VERSION = qv('0.1.0');

use base qw(Exporter);

our @EXPORT_OK = qw(COUNTRIES LOW_INCOME_COUNTRIES);
our %EXPORT_TAGS = ( 'ALL' => \@EXPORT_OK );

sub LOW_INCOME_COUNTRIES {
  return [
    q(Afghanistan),
    q(Albania),
    q(Algeria),
    q(American Samoa),
    q(Angola),
    q(Argentina),
    q(Armenia),
    q(Azerbaijan),
    q(Bangladesh),
    q(Belarus),
    q(Belize),
    q(Benin),
    q(Bhutan),
    q(Bolivia),
    q(Bosnia and Herzegovina),
    q(Botswana),
    q(Brazil),
    q(Bulgaria),
    q(Burkina Faso),
    q(Burundi),
    q(Cambodia),
    q(Cameroon),
    q(Cape Verde),
    q(Central African Republic),
    q(Chad),
    q(Chile),
    q(China),
    q(C&ocirc;te d'Ivoire),
    q(Colombia),
    q(Comoros),
    q(Congo, Dem. Rep),
    q(Congo, Rep.),
    q(Costa Rica),
    q(Cuba),
    q(Djibouti),
    q(Dominica),
    q(Dominican Republic),
    q(Ecuador),
    q(Egypt, Arab Rep.),
    q(El Salvador),
    q(Eritrea),
    q(Ethiopia),
    q(Fiji),
    q(Gabon),
    q(Gambia, The),
    q(Georgia),
    q(Ghana),
    q(Grenada),
    q(Guatemala),
    q(Guinea),
    q(Guinea-Bisau),
    q(Guyana),
    q(Haiti),
    q(Honduras),
    q(India),
    q(Indonesia),
    q(Iran, Islamic Rep.),
    q(Iraq),
    q(Jamaica),
    q(Jordan),
    q(Kazakhstan),
    q(Kenya),
    q(Kiribati),
    q(Korea, Dem Rep.),
    q(Kosovo),
    q(Kyrgyz Republic),
    q(Lao PDR),
    q(Latvia),
    q(Lebanon),
    q(Lesotho),
    q(Liberia),
    q(Libya),
    q(Lithuania),
    q(Macedonia, FYR),
    q(Madagascar),
    q(Malawi),
    q(Malaysia),
    q(Maldives),
    q(Mali),
    q(Marshall Islands),
    q(Mauritania),
    q(Mauritius),
    q(Mayotte),
    q(Mexico),
    q(Micronesia, Fed. Sts.),
    q(Moldova),
    q(Mongolia),
    q(Montenegro),
    q(Morocco),
    q(Mozambique),
    q(Myanmar),
    q(Namibia),
    q(Nepal),
    q(Nicaragua),
    q(Niger),
    q(Nigeria),
    q(Pakistan),
    q(Palau),
    q(Panama),
    q(Papua New Guinea),
    q(Paraguay),
    q(Peru),
    q(Philippines),
    q(Poland),
    q(Romania),
    q(Russian Federation),
    q(Rwanda),
    q(Samoa),
    q(Sao Tome and Principe),
    q(Senegal),
    q(Serbia),
    q(Seychelles),
    q(Sierra Leone),
    q(Solomon Islands),
    q(Somalia),
    q(South Africa),
    q(Sri Lanka),
    q(St. Kitts and Nevis),
    q(St. Lucia),
    q(St. Vincent and the Grenadines),
    q(Sudan),
    q(Suriname),
    q(Swaziland),
    q(Syrian Arab Republic),
    q(Tajikistan),
    q(Tanzania),
    q(Thailand),
    q(Timor-Leste),
    q(Togo),
    q(Tonga),
    q(Tunisia),
    q(Turkey),
    q(Turkmenistan),
    q(Uganda),
    q(Ukraine),
    q(Uruguay),
    q(Uzbekistan),
    q(Vanuatu),
    q(Venezuela, RB),
    q(Vietnam),
    q(West Bank and Gaza),
    q(Yemen, Rep.),
    q(Zambia),
    q(Zimbabwe),
  ];
}

sub COUNTRIES {
  return [
    q(Afghanistan),                                  q(&Aring;land Islands),
    q(Albania),                                      q(Algeria),
    q(American Samoa),                               q(Andorra),
    q(Angola),                                       q(Anguilla),
    q(Antarctica),                                   q(Antigua and Barbuda),
    q(Argentina),                                    q(Armenia),
    q(Aruba),                                        q(Australia),
    q(Austria),                                      q(Azerbaijan),
    q(Bahamas),                                      q(Bahrain),
    q(Bangladesh),                                   q(Barbados),
    q(Belarus),                                      q(Belgium),
    q(Belize),                                       q(Benin),
    q(Bermuda),                                      q(Bhutan),
    q(Bolivia, Plurinational State of),              q(Bosnia and Herzegovina),
    q(Botswana),                                     q(Bouvet Island),
    q(Brazil),                                       q(British Indian Ocean Territory),
    q(Brunei Darussalam),                            q(Bulgaria),
    q(Burkina Faso),                                 q(Burundi),
    q(Cambodia),                                     q(Cameroon),
    q(Canada),                                       q(Cape Verde),
    q(Cayman Islands),                               q(Central African Republic),
    q(Chad),                                         q(Chile),
    q(China),                                        q(Christmas Island),
    q(Cocos (Keeling) Islands),                      q(Colombia),
    q(Comoros),                                      q(Congo),
    q(Congo, the Democratic Republic of the),        q(Cook Islands),
    q(Costa Rica),                                   q(C&ocirc;te d'Ivoire),
    q(Croatia),                                      q(Cuba),
    q(Cyprus),                                       q(Czech Republic),
    q(Denmark),                                      q(Djibouti),
    q(Dominica),                                     q(Dominican Republic),
    q(Ecuador),                                      q(Egypt),
    q(El Salvador),                                  q(Equatorial Guinea),
    q(Eritrea),                                      q(Estonia),
    q(Ethiopia),                                     q(Falkland Islands (Malvinas)),
    q(Faroe Islands),                                q(Fiji),
    q(Finland),                                      q(France),
    q(French Guiana),                                q(French Polynesia),
    q(French Southern Territories),                  q(Gabon),
    q(Gambia),                                       q(Georgia),
    q(Germany),                                      q(Ghana),
    q(Gibraltar),                                    q(Greece),
    q(Greenland),                                    q(Grenada),
    q(Guadeloupe),                                   q(Guam),
    q(Guatemala),                                    q(Guernsey),
    q(Guinea),                                       q(Guinea-Bissau),
    q(Guyana),                                       q(Haiti),
    q(Heard Island and McDonald Islands),            q(Holy See (Vatican City State)),
    q(Honduras),                                     q(Hong Kong),
    q(Hungary),                                      q(Iceland),
    q(India),                                        q(Indonesia),
    q(Iran, Islamic Republic of),                    q(Iraq),
    q(Ireland),                                      q(Isle of Man),
    q(Israel),                                       q(Italy),
    q(Jamaica),                                      q(Japan),
    q(Jersey),                                       q(Jordan),
    q(Kazakhstan),                                   q(Kenya),
    q(Kiribati),                                     q(Korea, Democratic People's Republic of),
    q(Korea, Republic of),                           q(Kuwait),
    q(Kyrgyzstan),                                   q(Lao People's Democratic Republic),
    q(Latvia),                                       q(Lebanon),
    q(Lesotho),                                      q(Liberia),
    q(Libyan Arab Jamahiriya),                       q(Liechtenstein),
    q(Lithuania),                                    q(Luxembourg),
    q(Macao),                                        q(Macedonia, the former Yugoslav Republic of),
    q(Madagascar),                                   q(Malawi),
    q(Malaysia),                                     q(Maldives),
    q(Mali),                                         q(Malta),
    q(Marshall Islands),                             q(Martinique),
    q(Mauritania),                                   q(Mauritius),
    q(Mayotte),                                      q(Mexico),
    q(Micronesia, Federated States of),              q(Moldova, Republic of),
    q(Monaco),                                       q(Mongolia),
    q(Montenegro),                                   q(Montserrat),
    q(Morocco),                                      q(Mozambique),
    q(Myanmar),                                      q(Namibia),
    q(Nauru),                                        q(Nepal),
    q(Netherlands),                                  q(Netherlands Antilles),
    q(New Caledonia),                                q(New Zealand),
    q(Nicaragua),                                    q(Niger),
    q(Nigeria),                                      q(Niue),
    q(Norfolk Island),                               q(Northern Mariana Islands),
    q(Norway),                                       q(Oman),
    q(Pakistan),                                     q(Palau),
    q(Palestinian Territory, Occupied),              q(Panama),
    q(Papua New Guinea),                             q(Paraguay),
    q(Peru),                                         q(Philippines),
    q(Pitcairn),                                     q(Poland),
    q(Portugal),                                     q(Puerto Rico),
    q(Qatar),                                        q(R&eacute;union),
    q(Romania),                                      q(Russian Federation),
    q(Rwanda),                                       q(Saint Barth&eacute;lemy),
    q(Saint Helena),                                 q(Saint Kitts and Nevis),
    q(Saint Lucia),                                  q(Saint Martin (French part)),
    q(Saint Pierre and Miquelon),                    q(Saint Vincent and the Grenadines),
    q(Samoa),                                        q(San Marino),
    q(Sao Tome and Principe),                        q(Saudi Arabia),
    q(Senegal),                                      q(Serbia),
    q(Seychelles),                                   q(Sierra Leone),
    q(Singapore),                                    q(Slovakia),
    q(Slovenia),                                     q(Solomon Islands),
    q(Somalia),                                      q(South Africa),
    q(South Georgia and the South Sandwich Islands), q(Spain),
    q(Sri Lanka),                                    q(Sudan),
    q(Suriname),                                     q(Svalbard and Jan Mayen),
    q(Swaziland),                                    q(Sweden),
    q(Switzerland),                                  q(Syrian Arab Republic),
    q(Taiwan, Province of China),                    q(Tajikistan),
    q(Tanzania, United Republic of),                 q(Thailand),
    q(Timor-Leste),                                  q(Togo),
    q(Tokelau),                                      q(Tonga),
    q(Trinidad and Tobago),                          q(Tunisia),
    q(Turkey),                                       q(Turkmenistan),
    q(Turks and Caicos Islands),                     q(Tuvalu),
    q(Uganda),                                       q(Ukraine),
    q(United Arab Emirates),                         q(United Kingdom),
    q(United States),                                q(United States Minor Outlying Islands),
    q(Uruguay),                                      q(Uzbekistan),
    q(Vanuatu),                                      q(Venezuela, Bolivarian Republic of),
    q(Viet Nam),                                     q(Virgin Islands, British),
    q(Virgin Islands, U.S.),                         q(Wallis and Futuna),
    q(Western Sahara),                               q(Yemen),
    q(Zambia),                                       q(Zimbabwe),
  ];
}

1;
